### PR TITLE
Update slater theme package dependencies

### PR DESCRIPTION
**Pull request by Jore**
This updates `operator` and `picoapp` in the theme to the latest version

### CODE REVIEW

**Comment by Jore** [comment]
Just realised there are breaking changes in `picoapp`. I will amend this pull request when I get a chance.

**Comment by estrattonbailey** [comment]
@Jore thank you! Really appreciate it, and your contributions to these other libraries :)

I noticed you patched the version, good call. I'm not sure it's needed though, since when I publish with Lerna it'll update those values and reset the git `head` values in the package file. If you don't mind, could you please squash those changes out so the commit is only the package updates? Thanks!

**Comment by Jore** [comment]
No worries, all fixed now.

**Comment by estrattonbailey** [comment]
@Jore just published updated `evx` and `picoapp`, if you'd like to update this PR. No stress, I can as well.

**Comment by Jore** [comment]
I will update now

**Comment by tomaszbujnowicz** [comment]
Guys, does everything work for you after the update?
I got this https://take.ms/GuDBA

I also tried to make a clean install and got the same error.
Do you know what might be wrong?

**Pull request merged**
